[package]
name = "ch5"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "sturct1"
path = "src/struct.rs"

[[bin]]
name = "sturct2"
path = "src/struct2.rs"

[dependencies]
